apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-service-deployment
  namespace: group2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile-service
  template:
    metadata:
      labels:
        app: userprofile-service
    spec:
      containers:
      - name: userprofile-service
        image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2-user-eks-cp:user
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://g2-rds.cjas2m28ehia.ap-northeast-3.rds.amazonaws.com:3306/ShareIdea?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"  # Username
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Password123"  # Password
        - name: SERVER_PORT
          value: "8082"
      restartPolicy: Always
