apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: group2
spec:
  selector:
    app: userprofile-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort
